version: '3'

services:
  map:
    build: ./tile
    environment:
      - THREADS=4
    volumes:
      - ./data/tile-data:/var/lib/postgresql/12/main
      - ./data/rendered:/var/lib/mod_tile
      - ./data.osm.pbf:/data.osm.pbf
    ports:
      - "3000:80"
  nominatim:
    build: ./nominatim
    environment:
      - TILE_URL=http://localhost:3000
    volumes:
      - ./data/nominatim-data:/var/lib/postgresql/9.5/main
      - ./data.osm.pbf:/data/data.osm.pbf
    ports:
      - "8080:8080"
